[package]
  cjc-version = "1.0.0"
  name = "hello_static"
  description = "statically compiled hello world example"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "executable"
  compile-option = "--static --disable-reflection --static-std -O1"
  override-compile-option = "--disable-reflection --static-std -O1"
  link-option = "-s"
  package-configuration = {}

[dependencies]
  nappgui4cj = { path = "../../", output-type = "static" }

[target.aarch64-unknown-linux-gnu]
  link-option = "-lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0"

[target.x86_64-unknown-linux-gnu]
  link-option = "-lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0"

[target.x86_64-w64-mingw32]
  compile-option = "./res/resource.o"
  link-option = "--subsystem windows -lc++ -lcomctl32 -lcomdlg32 -lgdi32 -lgdiplus -lshlwapi -luxtheme -lws2_32"
