[package]
  cjc-version = "1.0.0"
  name = "casino"
  description = "casino example library"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "dynamic"
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
  link-option = ""
  package-configuration = {}

[dependencies]
  nappgui4cj = { path = "../../" }

[target.x86_64-w64-mingw32]
  link-option = "--subsystem windows"
